### ISSUE TITLE
Composite action for `tests` in release workflow

### ISSUE THREAD

**Issue by vchrombie** [chaoss/grimoirelab-github-actions#3]
We have composite actions for the `build`, `release`, and `publish` steps. How about a composite action for `tests` too?

Poetry now has plugin support and there is [poetry-plugin-export](https://github.com/python-poetry/poetry-plugin-export) plugin which exports the dependencies to a txt file. The dev dependencies can be exported as

```
$ poetry export --without-hashes -f requirements.txt --output requirements-dev.txt --only dev
```
References:
- https://github.com/python-poetry/poetry/issues/1441#issuecomment-1140246353
- https://github.com/python-poetry/poetry/issues/2572#issuecomment-1175703869

We can attempt to add the current steps to create a composite action that can be used similar to the other steps.

WDYT? @sduenas @jjmerchante

**Comment by vchrombie** [comment]
IMO, migrating to the poetry-export-plugin at least is a good option since [peodd](https://github.com/vchrombie/peodd) is a pet project (which does the job for now but might create complications in the future).

If we choose to not create a composite action, we can replace peodd to use the poetry export in the individual components workflow.

**Comment by vchrombie** [comment]
I have given it a try and came up with this
https://github.com/vchrombie/grimoirelab-github-actions/blob/ba35c00fc9d0f6a6d961b36b0ba3330a488b01c6/tests/action.yml

Tested it here
https://github.com/vchrombie/grimoirelab-perceval-zulip/actions/runs/2657780587

**Comment by sduenas** [comment]
> IMO, migrating to the poetry-export-plugin at least is a good option since [peodd](https://github.com/vchrombie/peodd) is a pet project (which does the job for now but might create complications in the future).
> 
> If we choose to not create a composite action, we can replace peodd to use the poetry export in the individual components workflow.

Yes, also, we have the problem that packages are not created with the exact versions defined in `poetry.lock` so that's why the last PR fixes the problem.

**Comment by sduenas** [comment]
I'd like to have the same for `tests`but, I'm not sure if it's possible. Not all tests are executed in the same way.

**Comment by vchrombie** [comment]
> I'd like to have the same for `tests` but, I'm not sure if it's possible. Not all tests are executed in the same way.

Yeah, it now makes sense to me. Sorting Hat has a different test suite execution or something similar scenario. So, in that case, I feel we can drop this idea and leave how the workflow right now is.

But, at least we can use poetry export instead of the peodd tool. WDYT @sduenas?

**Comment by vchrombie** [comment]
It makes sense that the tests are executed differently in the tools, so closing this issue.
